### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by pranaybathini** [hackthepart/HawkEye#6]
`
Traceback (most recent call last):                                                                                       `
  `File "scanner.py", line 108, in <module>`
`    defaultInterface = getDefaultInterface()`
 ` File "scanner.py", line 22, in getDefaultInterface`
    `network, netmask, _, interface, address = max(iface_routes, key=lambda item:item[1])`
`ValueError: too many values to unpack`

**Comment by pranaybathini** [comment]
solution 1 -
`network, netmask, _, interface, address,metric = max(iface_routes, key=lambda item:item[1])`
solution 2-
upgrade pip command by **pip install --upgrade pip**
If you are still facing any issue refer [https://pip.pypa.io/en/stable/installing/](url)
